//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qr2web.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("qr2web.Resources.Strings.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want proceed?.
        /// </summary>
        internal static string ExternaLinkAppProceed {
            get {
                return ResourceManager.GetString("ExternaLinkAppProceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External Link.
        /// </summary>
        internal static string ExternalLink {
            get {
                return ResourceManager.GetString("ExternalLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The page want to open an external link.
        /// </summary>
        internal static string ExternalLinkAppWantOpen {
            get {
                return ResourceManager.GetString("ExternalLinkAppWantOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External Links are not allowed.
        /// </summary>
        internal static string ExternalLinkNotAllowed {
            get {
                return ResourceManager.GetString("ExternalLinkNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string MenuAbout {
            get {
                return ResourceManager.GetString("MenuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string MenuHelp {
            get {
                return ResourceManager.GetString("MenuHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string MenuHome {
            get {
                return ResourceManager.GetString("MenuHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string MenuOptions {
            get {
                return ResourceManager.GetString("MenuOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string MenuRefresh {
            get {
                return ResourceManager.GetString("MenuRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepted Barcodes.
        /// </summary>
        internal static string OptionsPageAcceptedBarcodes {
            get {
                return ResourceManager.GetString("OptionsPageAcceptedBarcodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Others 1D.
        /// </summary>
        internal static string OptionsPageAcceptedOther1d {
            get {
                return ResourceManager.GetString("OptionsPageAcceptedOther1d", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow External Links.
        /// </summary>
        internal static string OptionsPageAlloweExternalLinks {
            get {
                return ResourceManager.GetString("OptionsPageAlloweExternalLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Options.
        /// </summary>
        internal static string OptionsPageAppOptions {
            get {
                return ResourceManager.GetString("OptionsPageAppOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force Background Activity.
        /// </summary>
        internal static string OptionsPageForceBackgroundActivity {
            get {
                return ResourceManager.GetString("OptionsPageForceBackgroundActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force Portrait.
        /// </summary>
        internal static string OptionsPageForcePortrait {
            get {
                return ResourceManager.GetString("OptionsPageForcePortrait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forward Position.
        /// </summary>
        internal static string OptionsPageForwardLocation {
            get {
                return ResourceManager.GetString("OptionsPageForwardLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Page.
        /// </summary>
        internal static string OptionsPageHomePage {
            get {
                return ResourceManager.GetString("OptionsPageHomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string OptionsPageLanguage {
            get {
                return ResourceManager.GetString("OptionsPageLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan Keyboard.
        /// </summary>
        internal static string OptionsPageScanKeyboard {
            get {
                return ResourceManager.GetString("OptionsPageScanKeyboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan Options.
        /// </summary>
        internal static string OptionsPageScanOptions {
            get {
                return ResourceManager.GetString("OptionsPageScanOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Scan Button.
        /// </summary>
        internal static string OptionsPageShowScanButton {
            get {
                return ResourceManager.GetString("OptionsPageShowScanButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string OptionsPageTitle {
            get {
                return ResourceManager.GetString("OptionsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use History.
        /// </summary>
        internal static string OptionsPageUseHistory {
            get {
                return ResourceManager.GetString("OptionsPageUseHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string ScanPageCancel {
            get {
                return ResourceManager.GetString("ScanPageCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCANNING....
        /// </summary>
        internal static string ScanPageScanning {
            get {
                return ResourceManager.GetString("ScanPageScanning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STARTING CAMERA....
        /// </summary>
        internal static string ScanPageStartCamera {
            get {
                return ResourceManager.GetString("ScanPageStartCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Settings.
        /// </summary>
        internal static string ScanParamAppSettings {
            get {
                return ResourceManager.GetString("ScanParamAppSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New configurations found.
        /// </summary>
        internal static string ScanParamNewFound {
            get {
                return ResourceManager.GetString("ScanParamNewFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New configuration found.
        /// </summary>
        internal static string ScanParamNewFound1 {
            get {
                return ResourceManager.GetString("ScanParamNewFound1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want save it?.
        /// </summary>
        internal static string ScanParamNewSave {
            get {
                return ResourceManager.GetString("ScanParamNewSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no valid parameters.
        /// </summary>
        internal static string ScanParamNoValid {
            get {
                return ResourceManager.GetString("ScanParamNoValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New parameters saved.
        /// </summary>
        internal static string ScanParamSaved {
            get {
                return ResourceManager.GetString("ScanParamSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
